/**
 * @typedef {Object} TrustedHTML
 * @property {boolean} __isTrusted
 */

/**
 * A tagged template literal that escapes values unless they are marked as trusted.
 * @param {TemplateStringsArray} strings
 * @param {...*} values
 * @returns {string & TrustedHTML}
 */
const html = (strings, ...values) => {
	const result = strings.reduce((acc, str, i) => {
		let val = values[i] ?? "";

		// Handle Arrays (like those generated by .map())
		if (Array.isArray(val)) {
			val = val
				.map((item) =>
					item && typeof item === "object" && item.__isTrusted
						? item.toString()
						: escapeHtml(String(item)),
				)
				.join("");
		}
		// Handle single TrustedHTML objects
		else if (val && typeof val === "object" && val.__isTrusted) {
			val = val.toString();
		}
		// Handle primitive strings/numbers
		else {
			val = escapeHtml(String(val));
		}

		return acc + str + val;
	}, "");

	return Object.assign(result, { __isTrusted: true });
};

/**
 * Helper to escape HTML characters
 * @param {string} str
 * @returns {string}
 */
function escapeHtml(str) {
	/** @type {Record<string, string>} */
	const escapeMap = {
		"&": "&amp;",
		"<": "&lt;",
		">": "&gt;",
		'"': "&quot;",
		"'": "&#39;",
	};
	return str.replace(/[&<>"']/g, (m) => escapeMap[m]);
}

export { html };
